language: python
sudo: false
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=py26-1.4.X
  - TOXENV=py27-1.4.X
  - TOXENV=py27-1.7.X
  - TOXENV=py32-1.7.X
  - TOXENV=py33-1.7.X
  - TOXENV=py34-1.7.X
  - TOXENV=py27-1.8.X
  - TOXENV=py32-1.8.X
  - TOXENV=py33-1.8.X
  - TOXENV=py34-1.8.X
# https://github.com/travis-ci/travis-ci/issues/4794
matrix:
  include:
    - python: 3.5
      env:
        - TOXENV=py35-1.8.X
notifications:
  irc: "irc.freenode.org#django-compressor"

after_success:
  - pip install codecov
  - codecov
