language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
  - export DJANGO_SETTINGS_MODULE=compressor.test_settings
  - sudo apt-get update
  - sudo apt-get install csstidy libxml2-dev libxslt-dev
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  # - flake8 compressor --ignore=E501
script:
  - django-admin.py test compressor
env:
  - DJANGO=1.3.1
  - DJANGO=1.4
branches:
  only:
    - develop
notifications:
  irc: "irc.freenode.org#django-compressor"
