language: python
sudo: false
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=py27-1.11.X
  - TOXENV=py34-1.11.X
  - TOXENV=py34-2.0.X
# https://github.com/travis-ci/travis-ci/issues/4794
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-1.11.X
    - python: 3.6
      env: TOXENV=py36-1.11.X
    - python: 3.5
      env: TOXENV=py35-2.0.X
    - python: 3.6
      env: TOXENV=py36-2.0.X
notifications:
  irc: "irc.freenode.org#django-compressor"
after_success:
  - pip install codecov
  - codecov
